name: Build and Run

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with: 
          node-version: '14'

      - name: Install Dependncies
        run:  sudo npm install
      
      - name: Lint with eslint
        run: |
          npx eslint --fix .
      - name: Install lizard
        run: pip install lizard

      - name: Limit complexity
        run: $HOME/.local/bin/lizard -l javascript --CCN 3 src/
        
      - name: Run and collect coverage
        run: npx nyc --reporter=html --reporter=text npm run test

      - name: Upload coverage
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: ./coverage
          retention-days: 21
